version: '3.7'

services: 
    web: 
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        ports:
            - 5555:5000
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        depends_on: 
            - db
    db:
        image: postgres:12-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - ./.env.db
    nginx:
        build: ./nginx
        ports: 
            - 80:80
        depends_on: 
            - web

volumes: 
    postgres_data:
    
        
